Repository marcosnils/bin, pull requests merged in 2021-03, with the labels that each got.

#45 Gitlab generic packages
  go.mod
  go.sum
  pkg/assets/assets.go
  pkg/assets/assets_test.go
  pkg/config/config.go
  pkg/providers/gitlab.go
Labels: enhancement

#51 Fix package files pagination
  pkg/providers/gitlab.go
Labels: bug

#55 Support "win" as Windows OS name component
  pkg/assets/assets_test.go
  pkg/config/config.go
Labels: enhancement

#56 Prevent semantic downgrades in `bin update`
  cmd/update.go
  cmd/update_test.go
  go.mod
  go.sum
Labels: enhancement

#66 Copied CONTRIBUTING and CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#64 Add golangci-lint, fix linting issues
  .github/workflows/build.yml
  .golangci.yml
  CONTRIBUTING.md
  cmd/error.go
  cmd/list.go
  cmd/prune.go
  cmd/remove.go
  cmd/update.go
  pkg/assets/assets.go
  pkg/config/config.go
  pkg/providers/docker.go
  pkg/providers/github.go
  pkg/providers/gitlab.go
  pkg/providers/hashicorp.go
Labels: enhancement

#76 Support OS specific extensions
  pkg/assets/assets.go
  pkg/assets/assets_test.go
  pkg/config/config.go
Labels: enhancement

#74 Sort binaries by path in `bin ls`
  cmd/list.go
Labels: enhancement

#82 Filter assets inside Zip archives
  pkg/assets/assets.go
Labels: enhancement

#81 Support (.tar).bz2 archives
  pkg/assets/assets.go
  pkg/assets/assets_test.go
Labels: enhancement
